os: osx
language: swift
xcode_workspace: Stitch.xcworkspace
xcode_scheme: StitchSDK
script:
  - pod install
deploy:
  provider: script
  script: echo "Fake deploy"
  skip_cleanup: true
addons:
  artifacts: true
